[package]
name = "outpost_config"
version = "0.1.0"
authors = ["j-brn <me@jbrn.eu>", "jonas32 <m@x32.me>"]
edition = "2018"

[dependencies]
thiserror = "1.0.19"
serde = "1.0.111"
serde_json = "1.0.53"